require("config.plugins")
require("config.options")
require("config.telescope")
require("config.nvim-tree")
require("config.statusline")
require("config.bufferline")
-- require("config.treesitter")
require("config.gitsigns")
-- require("config.lsp")
require("config.markdow-preview")
require("config.keymaps")
require("config.autocmds")
