vim.keymap.set("n", "<C-i>", ":Neoformat<CR>", {})
vim.keymap.set("x", "<leader>p", '"_dP')
vim.keymap.set("x", "<leader>d", '"_d')
vim.keymap.set("n", "<leader>d", '"_d')
vim.keymap.set("n", "<leader>ll", ":VimtexCompile<Cr>", {})
vim.keymap.set("n", "<leader>le", ":VimtexErrors<Cr>", {})
vim.keymap.set("n", "<leader>j", ":bprevious<CR>")
vim.keymap.set("n", "<leader>k", ":bnext<CR>")
vim.keymap.set("n", "<leader>bc", ":bdelete<CR>")
